############################################################
# Dockerfile to build jlib for gcc:4.9
# Based on Ubuntu Image
############################################################

# Set the base image to use to gcc:4.9
FROM gcc:4.9

# Set the file maintainer
MAINTAINER Joey Yandle

RUN apt-get update
RUN apt-get install -y sudo gdb
#RUN addgroup --gid 1000 dragon
#RUN useradd --uid 1000 --gid 1000 -G sudo dragon 

ENTRYPOINT /bin/bash
